version: '3'

services:
  snake-coin:
    build:
      context: .
    image: "amangion/snake-coin-backend:latest"
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_HOST=mongodb://mongo/snake-coin
      - MONGOOSE_DEBUG=true
      - DEBUG=snake-coin:*
    links:
      - mongo
  mongo:
    image: "mongo:3.4.2"
    ports:
      - "27017:27017"
